package example.mapper;

import example.model.Item;
import example.model.ItemExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DemoMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * item
     *
     * @mbg.generated Sat Nov 05 17:42:46 JST 2022
     */
    long countByExample(ItemExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * item
     *
     * @mbg.generated Sat Nov 05 17:42:46 JST 2022
     */
    int deleteByExample(ItemExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * item
     *
     * @mbg.generated Sat Nov 05 17:42:46 JST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * item
     *
     * @mbg.generated Sat Nov 05 17:42:46 JST 2022
     */
    int insert(Item row);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * item
     *
     * @mbg.generated Sat Nov 05 17:42:46 JST 2022
     */
    int insertSelective(Item row);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * item
     *
     * @mbg.generated Sat Nov 05 17:42:46 JST 2022
     */
    List<Item> selectByExample(ItemExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * item
     *
     * @mbg.generated Sat Nov 05 17:42:46 JST 2022
     */
    Item selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * item
     *
     * @mbg.generated Sat Nov 05 17:42:46 JST 2022
     */
    int updateByExampleSelective(@Param("row") Item row, @Param("example") ItemExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * item
     *
     * @mbg.generated Sat Nov 05 17:42:46 JST 2022
     */
    int updateByExample(@Param("row") Item row, @Param("example") ItemExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * item
     *
     * @mbg.generated Sat Nov 05 17:42:46 JST 2022
     */
    int updateByPrimaryKeySelective(Item row);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * item
     *
     * @mbg.generated Sat Nov 05 17:42:46 JST 2022
     */
    int updateByPrimaryKey(Item row);
}