version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/app/
permissions:
  - object: /home/ec2-user
    pattern: "app"
    owner: ec2-user
    group: ec2-user
    type:
      - directory
  - object: /home/ec2-user/app
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    mode: 444
    type:
      - file
hooks:
  ApplicationStart:
    - location: spring-boot-demo-restart.sh
      timeout: 300
      runas: root
